### ISSUE TITLE
About  Code

### ISSUE THREAD

**Issue by bzlff** [soniamartinot/Deep-GPR#1]
Hello😊, I am very interested in your work and the project you mentioned in your paper. I was looking forward to exploring the open-source code you mentioned, but I couldn't find it on your GitHub repository. Could you please provide more details about the open-source code and when you plan to upload it? I am eager to learn more about your project and would appreciate any information you can share. Thank you!

**Comment by soniamartinot** [comment]
Hello ! Thank you for your interest ! Unfortunately, I will not publish the code as it is now industrial code involved in a patent. Let me know if you wish to discuss further about the paper !
